oauth/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^oauth/vk/$', views.vk, name='vk'),
    url(r'^oauth/fb/$', views.fb, name='fb'),
    url(r'^oauth/gp/$', views.gp, name='gp'),
    url(r'^oauth/ya/$', views.ya, name='ya'),
]

diagram/forms.py
import datetime

from django.utils import timezone

from django import forms
from mainapp.base import Base as MainappBase

def get_now():
    
    now = MainappBase().datetime_localize(datetime.datetime.now())
    
    return now.strftime('%d-%m-%Y')

class UsersPeriod(forms.Form):
    
    date_from = forms.CharField(label='Начать с', initial=get_now, required=True, max_length=100)
    date_to = forms.CharField(label='Окончить по', initial=get_now, required=True, max_length=100)

diagram/templates/dynamic/dynamic.html
<div class="large-12 small-12 columns dynamic_diagram_wrapper open_sans" data-id="{{id}}">
	<div class="large-12 small-12 columns padding_standart">
		<div class="large-12 small-12 columns nopadding dynamic_title span_large"></div>
		<div class="large-12 small-12 columns nopadding dynamic_subtitle span_usual"></div>	
	</div>
	
	<div class="large-12 small-12 columns nopadding span_usual">
		<div class="large-2 small-6 columns span_usual diagram_choose_line display_table transition" data-type="all" data-id="{{id}}" style="float:left;">
			<div class="vertical_middle">
				<span class="vertical_middle">Всего:</span>
				<span class="diagram_choose_line_count"></span>	
			</div>
		</div>
		<div class="large-2 small-6 columns span_usual diagram_choose_line display_table transition" data-type="unique" data-id="{{id}}" style="float:left;">
			<div class="vertical_middle">
				<span class="vertical_middle">Уникальных:</span>
				<span class="diagram_choose_line_count"></span>	
			</div>
		</div>
		<div class="large-2 small-6 columns span_usual diagram_choose_line display_table transition" data-type="reprint" data-id="{{id}}" style="float:left;">
			<div class="vertical_middle">
				<span class="vertical_middle">Частичных копий:</span>
				<span class="diagram_choose_line_count"></span>	
			</div>
		</div>
		<div class="large-2 small-6 columns span_usual diagram_choose_line display_table transition" data-type="copy" data-id="{{id}}" style="float:left;">
			<div class="vertical_middle">
				<span class="vertical_middle">Полных копий:</span>
				<span class="diagram_choose_line_count"></span>
			</div>
		</div>
		<!-- <div class="large-2 small-6 columns span_usual diagram_choose_line display_table transition" data-type="incorrect" data-id="{{id}}" style="float:left;">
			<div class="vertical_middle">
				<span class="vertical_middle">Некорректных:</span>
				<span class="diagram_choose_line_count"></span>
			</div>
		</div> -->
	</div>
	<div id="dynamic{{id}}" class="diagram large-12 small-12 columns nopadding">
		

	</div>
	<div class="large-12 small-12 columns nopadding">
		<!-- <label for="dynamic_days_count" class="span_usual">
			За последние:
		</label> -->
		<select name="" id="dynamic_period_select">
			<option value="today">Сегодня</option>
			<option value="yesterday">Вчера</option>
			<option value="last 7 days" selected="selected">Последн. 7 дней</option>
			<option value="last 14 days">Последн. 14 дней</option>
			<option value="last 28 days">Последн. 28 дней</option>
			<option value="last 35 days">Последн. 35 дней</option>
			<option value="quarter begin">С начала квартала</option>
			<option value="current year">Текущий год</option>
			<option value="custom">Собственный</option>
		</select>
	</div>
</div>

diagram/templates/dynamic/pubs_list.html
<div class="large-12 small-12 columns nopadding span_usual open_sans" id="pubs_list">
    <table>
        <thead>
            <tr>
                <th>
                    № Пп
                </th>
                <th>
                    Заголовок
                </th>
                <th>
                    Дата
                </th>
            </tr>
        </thead>
        <tbody>
            {% for pub in pubs %}
                <tr>
                    <td>
                       {{forloop.counter}} 
                    </td>
                    <td>
                        {{pub.title}}
                    </td>
                    <td>
                        {{pub.date}}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

diagram/templates/dynamic/users_period.html
{% load custom_templates %}
<div class="large-12 small-12 columns nopadding">
    <form id="users_period">
        {% for field in form %}
            <div class="large-12 small-12 columns" id="{{field.name}}">
                <div class="large-12 small-12 columns nopadding span_usual">
                    {{field|label_with_classes:"span_usual"}}
                </div>
                <div class="large-12 small-12 columns nopadding">{{field}}</div>
            </div>
        {% endfor %}

        {% for field in form %}
            {% if field.errors %}
                {% for error in field.errors %}
                    <div class="large-12 small-12 columns" style="color:red;">
                        <span class="span_usual">{{field.label}}. {{error|escape}}</span>
                    </div>
                {% endfor %}
            {% endif %}
        {% endfor %}
    </form>
    <div class="large-12 small-12 columns padding_standart">
        <button class="span_usual button site_button" id="users_period_confirm">
            принять
        </button>
    </div>
</div>
<script>
    default_date = '{{default_date}}';
    
	$(function(){
		$('#id_date_from').fdatepicker({
            initialDate: default_date,
			format: 'dd-mm-yyyy',
			disableDblClickSelection: true,
			language: 'ru',
			//pickTime: true,
			weekStart: 1
		});
		$('#id_date_to').fdatepicker({
            initialDate: default_date,
			format: 'dd-mm-yyyy',
			disableDblClickSelection: true,
			language: 'ru',
			//pickTime: true,
			weekStart: 1
		});
	});
</script>